### ISSUE TITLE
Varying tile dimensions not supported?

### ISSUE THREAD

**Issue by mmontag** [baylej/tmx#26] opened 2016-11-06 03:59 UTC
Hi, I have a Tiled map with 16x16 tiles on layer 1 and 24x28 tiles on layer 2. 

In Tiled this appears to work fine. I can place a 24x28 tile in layer 2.  But TMX seems to be picky about varying tile size, and none of the 24x28 tiles are rendered in my game.

**Comment by baylej** [comment] 2016-11-06 16:45
Hello,
TMX does no rendering, it only loads the map in a datastructure, maybe you are using one of the example codes, the SDL2 or the Allegro5 example.
Please keep in mind that these examples are not feature complete and may have bugs, you can use them to make your own renderer though.

**Comment by baylej** [comment] 2016-11-07 10:42
Hi,
I tried to reproduce using this map: http://bayle.jonathan.free.fr/f/test_varying_tiles.zip
It uses 16x16 and 24x28 tiles, layer1 for 16x16 tiles and layer2 for 24x28 tiles (map tileheight and tilewidth are both set to 16), both the Allegro5 and the SDL2 examples have an alignment issue, but tiles on the layer2 are drawn!

I'll fix that alignment bug, but I'm closing this issue as I cannot reproduce.

If you want to reopen it, please provide a map that triggers the issue, thanks.

**Closed by baylej** 2016-11-07 10:42 UTC
